---
title: Canopy leaf area of an evergreen Eucalyptus woodland does not respond to elevated
  atmospheric [$CO_2$] but tracks water availability
author: "Remko Duursma"
date: "April 24, 2015"
output:
  word_document:
    reference_docx: manuscriptstyle.docx
  pdf_document: default
  html_document:
    number_sections: yes
csl: global-change-biology.csl
bibliography: references.bib
---


```{r echo=FALSE, message=FALSE}
library(knitr)
load("cache/lai_workspace.RData")
source("load.R")
library(broom)
options(scipen = 1, digits = 2)

# Main results
df <- facegap_cloudy_byring

# Some pre-calculations
caliblm <- calibrateToDrought(df)$lmfit

# Number of months of study
r <- range(df$Date)
nummon <- as.numeric(floor(difftime(r[2],r[1],units="weeks")/(52/12)))

# Range mean LAI
dfa <- summaryBy(LAI ~ Date, FUN=mean, na.rm=TRUE, data=df)
rangeLAI <- round(range(dfa$LAI),1)


# Some definitions of constants
.gambase <- 18


```


# Abstract {.unnumbered}

Leaf area, quantified by the leaf area index (*L*), is a crucial driver of forest productivity, water use, and energy balance. Because *L* responds to environmental drivers, it can represent an important feedback to climate change, but its responses to rising [$CO_2$] and water availability of unmanaged forests have been poorly quantified. We studied canopy leaf area dynamics for `r nummon` months in a native evergreen *Eucalyptus* woodland exposed to Free Air $CO_2$ Enrichment (the EucFACE experiment), in a temperate (hot summer) climate where water limitation is common. We hypothesized that, because of expected higher productivity and increased water-use efficiency, *L* should increase with elevated [$CO_2$]. We estimated *L* from diffuse canopy transmittance, and measured monthly leaf litter production. Contrary to expectation, *L* did not respond to elevated [$CO_2$] in this timeframe. We found that *L* varied between `r rangeLAI[1]` and `r rangeLAI[2]`, but did not show a clear annual pattern. Instead, dynamics of *L* showed a quick increase after heavy rainfall, and a steady during periods of low rainfall. Leaf litter production was correlated to changes in *L*, both during periods of decreasing *L* (when no leaf growth occurred), and during periods of increasing *L* (active shedding of old foliage when new leaf growth occurred). Leaf lifespan, estimated from mean *L* and total annual litter production, was significantly increased under elevated [$CO_2$] (p = 0.051). We discuss these results in the context of modelling phenology of evergreen woodlands in response to environmental drivers. 

*Keywords*: leaf area index, FACE, phenology, drought, litter production


# Introduction

Leaf area index (*L*) is an important ecosystem attribute underlying productivity of vegetation, [@Reich2012], and a key variable in land surface models [@Kala2013; @Walker2014]. *L* is a dynamic canopy property, as it is generally responsive to variation in water and nutrient availability, as demonstrated in experiments [@Herbert1995; @Hubbard2004; @White2010] and observational studies across rainfall gradients [@Ellis2008; @Iio2013; @Jin2013]. Ecosystem models generally predict that *L* increases in response to elevated atmospheric [$CO_2$] ($eC_a$) due to increased net carbon uptake [@DeKauwe2014; @Hatton1992; @Kergoat2002; @Zhu2012]. Also expected because increased quantum yield of photosynthesis in $eC_a$ would allow leaf retention into deeper shade [@Norby1999], but little empirical evidence is available on the response of *L* to $eC_a$ in mature forests [@Norby2011]. Quantifying the magnitude and direction of the $eC_a$ effect on *L* is crucial, as changes in *L* associated with climate change drivers such as increases in $C_a$ may provide an important feedback to climate change, and modify direct physiological responses to $C_a$ [@Tor-ngern2015; @Murray2012].

Direct effects of $eC_a$ on vegetation processes include an enhancement of photosynthesis and productivity, a decrease in stomatal conductance and leaf-level water use and an increase in the water-use efficiency [@Ainsworth2005; @Ellsworth2012]. Although numerous studies have been conducted on the response of physiology and plant growth to $eC_a$, very few of these inform the response of steady-state *L* to $eC_a$, because it requires a sufficiently mature forest to be exposed to free air $CO_2$ enrichment (FACE) [@Norby2011]. Increased carbon availability through enhanced photosynthesis under $eC_a$ does not necessarily lead to increases in *L*. Out of the six forest FACE studies that have been carried out worldwide, only broad-leaved deciduous aspen stands (in monoculture or mixed with birch) and needle-leaved evergreen pine stands showed increased *L* in response to $eC_a$ *L* [@Norby2011], although positive responses to $eC_a$ in terms of productivity were observed at all six sites. Interestingly, Norby and Zak [-@Norby2011] found a negative correlation between pre-treatment *L* and the responsiveness to $eC_a$, leading to the prediction that stands with low *L* will show a larger response to $eC_a$. Because diminished returns in increasing LAI in response to $eC_a$ when LAI is larger [@Norby2005].
 
In ecosystems where water availability limits productivity, we could expect $eC_a$ to further affect *L* [@Donohue2009], since $eC_a$ reduces stomatal conductance, and hence water use per unit of leaf area [@Warren2010] leading to increased soil water availability. These ‘water savings’ can be expected to lead to an increase in *L* in water-limited ecosystems under the idea that leaf area is closely coupled to water-balance. **Explain here or just before that we expect this because of the tight relationship between LAI and rainfall across gradients.** In support of this prediction, Donohue et al. [-@Donohue2013] attributed the observed global increase in *L* in arid and semi-arid areas over the last 30 years to rising $C_a$. Based on the same water-savings principle, we predict that *L* should also increase under $eC_a$ in water-limited forests. 

Most previous studies on *L* responses to environmental drivers have focused on the seasonal, mostly temperature and light-driven, timing of *L* dynamics observed in N-hemisphere forests (e.g. [@Richardson2012; @Savoy2015]) whereas *L* responses to fluctuations in water availability are qualitatively well-known (**more cites**), but poorly quantified. The *L* of broad-leaved evergreen trees that dominate forests in the southern hemisphere show particular sensitivity to water-availability [@Pook1985; @Specht1989; @Whitehead2004; @Pook1997; @Limousin2009].The strong relationship between *L* and rainfall observed across Australia [@Ellis2008; @Specht1989], and other continents [@Donohue2013; @Grier1977; @Jin2013] represents the adaptation of vegetation structure and density to long-term climate conditions. However, local *L* is also highly responsive to water availability at shorter time scales [@Pook1985; @Pook1997], driven by leaf turnover [@Misson2011] and leaf flushing and expansion [@Muller2011], which are both highly responsive to soil water availability. Nevertheless, few datasets are currently available at sufficiently high temporal resolution to allow modelling of water-driven changes in phenology [@Misson2011].

We estimated *L* from near-continuous measurements of canopy transmittance in a Eucalyptus-dominated woodland exposed to $eC_a$, the EucFACE experiment. The woodland stand at the EucFACE is frequently water-limited, allowing us to quantify the dynamics of *L*, and its components (litter fall and production) in response to water availability. We hypothesized that $eC_a$ would result in an increase in *L*, particularly during periods of water limitation, as water savings were expected to lead to longer retention of foliage under elevated $CO_2$. In addition, we expected that the low *L* that is typical of native *Eucalyptus*-dominated woodlands [@Whitehead2004] allowed a larger response to $eC_a$ [@Norby2011]. Our second objective was to quantify the temporal dynamics of *L*, in particular in relation to fluctuating water availability.


# Materials and Methods

## Site description and experimental design
The EucFACE experiment is located on an ancient alluvial ﬂoodplain about 5 km from the Hawkesbury River in western Sydney (Australia) at 30 m a.s.l. elevation (33°37'S, 150°44'E). It is located within a remnant patch of native Cumberland Plain woodland (Tozer, 2003). The vegetation, maintained in this location since the 1880’s, retains some old-growth trees and some re-growth vegetation though it has been undisturbed for ca. 70 years. The site is characterized by a humid temperate-subtropical transitional climate with a mean annual temperature of 17 °C and mean annual precipitation of 800 mm (Bureau of Meteorology, station 067105 in Richmond, NSW Australia; http://www.bom.gov.au).

The soil at the site is a loamy sand in the Clarendon Formation (Barton et al., 2010; Isbell, 2002), a slightly-acid, low-organic C, well-drained soil. The soil surface is a loamy sand with > 75% sand content, and from ca. 50 to 300 cm depth, soils are a sandy clay loam with > 30% silt and clay. The soil is nutrient poor, and a strong limitation of P on tree growth at the site has recently been demonstrated [@Crous2015]. Groundwater depth is 12.6 – 12.9 m below the soil surface. The woodland ranges in density from 600-1000 trees $ha^{-1}$. The vegetation consists of an open woodland (basal area before treatment, BA = `r mean(ba$BA)`, SE = `r sd(ba$BA)/sqrt(6)` m$^2$ ha$^{-1}$, n = 6 plots) with a single major canopy-forming tree (*Eucalyptus tereticornis* Sm.) with a minor component of *E. amplifolia* Naudin. The understory stratum is composed mainly of grass species dominated by *Microlaena stipoides* (Labill.) R.Br., with lower densities of forbs of *Commelina cyanea* R.Br., *Lobelia purpurascens* R.Br., *Dichondra repens* J.R.Forst. & G.Forst and occasional shrubs of *Breynia oblongifolia* (Mull.Arg.) Mull.Arg. and *Bursaria spinosa* Cav.

Within the EucFACE site, there are six 25-m diameter circular plots (designated hereafter as ‘rings’). Each ring comprises 32 vent pipes in a cylindrical frame extending above the tree canopy to 28 m high. Each vertical pipe is subtended by a control valve and is connected to a circular plenum [@Hendrey1999] through which a computer-controlled system modulates release of diluted $CO_2$ into the vegetation according to a proportional-integral-differential type of algorithm [@Lewin2009]. The vegetation within three randomly selected rings was exposed to a $CO_2$ mole fraction ($C_a$) higher than ambient starting in September 2012, whereas the other three rings were identical to the $CO_2$ treatment rings in infrastructure and instrumentation but received ambient $C_a$, and are used as control plots. The target diurnal $C_a$ for the rings exposed to $eC_a$ was 150 μmol $CO_2$ mol$^{-1}$ above ambient $C_a$ in full operation mode. However, $C_a$ was increased gradually for six months at a rate of ca. 30 μmol $CO_2$ mol$^{-1}$ month$^{-1}$ until full operation mode was reached (Figure 1a).

Air temperature was measured on top of the central tower of each ring (23.5 m height) with a HUMICAP sensor (HMP 155 Vaisala, Vantaa, Finland). Total precipitation was monitored with three automated tipping buckets (Tipping Bucket Rain gauge TB4, Hydrological Services Pty Ltd, Liverpool, NSW, Australia) located at the top of the central tower at 23.5 m height, in three of the rings. Total precipitation and mean temperature were logged every 15 minutes onto CR3000 data loggers. Soil volumetric water content was measured at two different locations in each ring with two sets of theta probes (ThetaProbe ML2x, Delta-T Devices Ltd, Cambridge, UK) installed at 5, 30, 75 cm depth and at the depth at which a hard pan with higher clay content was present (30-50cm depth depending on the ring).

## Terminology
In the following, we use the term ‘leaf’ area index (*L*) although the canopy and FACE rings contain non-leaf shading elements, i.e. woody stems and infrastructure. This avoids the need to switch between different terminologies when comparing temporal changes in *L* to litter production, and absolute values between different methods. The temporal changes in *L* are due to leaf area dynamics only, because infrastructure area is constant, and woody stem area is very nearly constant over the two-year study period since no tree mortality has occurred.

## Leaf litter production
In each ring, 8 litter cloth baskets with an area of 0.1979 $m^2$ were installed at 0.5m above the forest floor. Litter was collected approximately monthly, and leaves separated from other components such as twigs, bark, seeds, insect frass, etc. Litter production was converted to units of *L* using an estimate of specific leaf area (SLA) determined from 329 leaves collected from the tree canopies from May 2012 to May 2014 (`r get_sla()` cm$^2$ g$^{-1}$, SE=2.14). We did not find a significant effect of $C_a$ treatment on SLA (Ellsworth, unpublished data; Ben Moore, unpublished data).

## Estimation of leaf area index from digital photography
Leaf area index (*L*) was estimated from zenith canopy photographs following [@Macfarlane2007]. From October 2012 to October 2013, we took ca. monthly canopy photographs in each FACE ring. Photographs were taken in the morning on cloudy days. We took one photograph at each point of a 4 x 4 m grid established within each ring, unless obstructed by trees, yielding 20-23 photos per ring. Sampling points too close to either the vertical vent pipes (edges of the ring) or the central scaffolding tower were excluded. The camera was aligned with the north-south axis and set at 1.25 m height.  Camera lens was pointed directly upwards and levelled using a three axis bubble level. We used a Nikon D90 camera with a Nikon AF 50 mm lens (Nikon Corporation, Tokyo, Japan). To measure cover, the camera was set to automatic exposure, Aperture-Priority and automatic autofocus mode and F10 lens. Following recommendations by Jonckheere et al. [-@Jonckheere2005], we used the automated Ridler algorithm to threshold the canopy photos. We then calculated canopy transmittance (τ_p) from each canopy photo as the proportion of pixels with intensity in the blue band below that threshold. *L* from canopy photos (Lp) was calculated with a simple Beer-Lambert law (Eq. 1).

(1) $$L_p = -log(\tau_p)/k$$

where τ_p canopy transmission estimated from canopy photos, and we assumed that the extinction coefficient k = 0.5, following (Macfarlane et al., 2007) recommendation for eucalypt forests. 

## *L* from diffuse transmittance
In each of the six FACE rings, 3 photosynthetically active radiation (PAR) sensors (LI-190, Li-cor, Lincoln, NE, U.S.A.) were installed on metal posts at 1 m height similar to the approach used by Norby et al. 2003. Data were logged on data loggers (CR3000, Campbell Scientific Australia, Townsville, Australia) at minutely intervals from 15 Oct. 2012, and automatically uploaded every day to a data management system. At each ring, another PAR sensor was installed above the canopy, on a mast extending above a scaffolding tower in the centre of each ring at 23.5 m height. All PAR data were averaged in 30 min time steps. At a nearby site (within 2 km), we measured the diffuse fraction (Fdiff) of PAR at 30 min time step using a BF5 Sunshine sensor (Delta-T Instruments, Cambridge, UK) installed on a tower extending above the canopy. For determination of *L*, we used only highly diffuse conditions, where Fdiff > 0.98. We further trimmed the data by excluding low solar elevation (< 10°), because, for unknown reasons, measured canopy transmittance was more variable at these low solar angles. Finally canopy transmittance was calculated for every 30-min time step as,

(2) $$\tau_d = \bar{Q}_{below} / Q_{above}$$

where $\tau_d$ is diffuse canopy transmittance, Qabove is above canopy PAR (µmol m$^{-2}s^{-1}$), and Q$_{below}$ is the average PAR across the three sub-canopy PAR sensors in each FACE ring. We then calculated daily averages of $\tau_d$, excluding days where less than 4 time steps were available, and days where the standard deviation among the three PAR sensors in a ring was  > 0.03 (in units of $\tau_d$).

We then estimated leaf area index (*L*) from $\tau_d$ ($L_\tau$), following (Campbell and Norman, 2000). We assumed that leaves had a spherical leaf angle distribution, and leaves were randomly distributed in space. We recognize that these assumptions are very likely violated, but we account for this bias by calibrating the *L* estimate to leaf litter production as further detailed below. Diffuse transmittance of a canopy is a function of the *L* by integrating the Beer-Lambert law across the entire sky hemisphere, and accounting for differences in extinction coefficient with different viewing angles (because of leaf angle and longer path length through the canopy at low solar angles).


(3) $$\tau_d = 2\int_0^{\pi/2} e^{-LG(\theta)/cos(\theta)}sin(\theta)cos(\theta)d\theta$$


where $\theta$ is the solar zenith angle, G($\theta$) is the foliage projection function in the direction of the beam (Campbell and Norman, 2000). Because we assumed a spherical leaf angle distribution, G(θ) = 0.5 (Stenberg, 2006). We solved numerically for *L* in Eq. 3, using a smooth integration over $\theta$, yielding *L*τ. 

To overcome violations in the assumptions underlying Eq. 3, we calibrated *L* against litter production. We estimated *L* from $\tau_d$ ($L_\tau$) and calibrating against cumulative litter production during a drought period in 2013 (indicated in Fig. 1). We selected a period of sustained drought in 2013 (14 July 2013 – 12 Nov 2013), during which no leaf growth occurred but *L* decreased steadily (and thus $\tau_d$ increased steadily, see Fig. 1). During this period, only 42 mm precipitation was recorded, which was the second driest July-October period recorded at a nearby (<2km) weather station in operation since 1881 (compared to a long-term average of 188 mm for this period). A total of n=11 days with sufficiently diffuse conditions to estimate $\tau_d$  were available during this period. In theory, cumulative *L* leaf litter production ($P_L$, expressed in units of *L*) during that period should thus match the observed decrease in *L* estimated from canopy transmittance. We calibrated equation (4), 

(4) $$c(L_{\tau,t} - L_{\tau,t=0}) = \int_0^t P_Ldt$$

where *c* is a calibration parameter, $L_{\tau,t=0}$ is $L_\tau$ at the start of the drought period. We used linear regression without intercept to estimate *c* in Eq. 4 as `r calib` (SE = `r tidy(caliblm)$std.error`). It should be stressed that even after calibration with litter production, $L_\tau$ still includes stem and infrastructure area (see Terminology), because this approximately constant area cancels out in the left-hand side of Eq. 4.

## Data analysis
We used generalized additive models (gam) for all analyses of *L* and $\tau_d$ timeseries (Wood, 2006), using the *mgcv* package in R [@RCT2015]. For all time-series, we used a base of `r .gambase` when fitting the gams, which resulted in biologically realistic smoothed *L* dynamics. In all fits, we used the FACE ring as a random effect, except when we analysed average *L* across all rings (Fig. 7). We estimated the derivative of the fitted gam, including confidence intervals for the derivative, following Simpson (2014). For comparison between *L* from photos and PAR transmittance, we used simple linear regression. To test for effects of $C_a$ treatment on $L_\tau$ and litter production, we used linear-mixed effects models with FACE ring as the random effect, and $C_a$ treatment and date as a factor.

To assess effects of $eC_a$ on $L_\tau$, we accounted for pre-treatment differences in canopy structure, as follows. The average $L_\tau$ over the entire period was well correlated with basal area (BA) measured prior to the onset of the $eC_a$ treatment across the FACE rings (Fig. 3). Because the EucFACE woodland is well established, the differences in BA are not due to $C_a$ treatment effects, but instead represent natural variation within the woodland. We then calculated the deviation of actual $L_\tau$ from the fitted relationship with BA shown in Fig. 3, to yield a ‘*L* anomaly’. This way, we effectively used BA as a covariate in the analysis to account for pre-treatment variation. 

# Results

Canopy transmittance ($\tau_d$) varied between 0.10 and 0.36, with much temporal variation, and substantial absolute differences between the individual FACE rings (Fig. 1).  However, temporal trends were very similar between the rings. Since the understorey comprises mostly grasses and forbs, and the PAR sensors were installed at 1 m height, this variation is due to the overstorey trees only. 

An outbreak of psyllids (*Cardiaspina* sp.), a tiny sap-feeding insect, resulted in rapid loss of canopy leaf area in one of the rings, starting in Sept. 2014 (for description of a similar outbreak in *Eucalyptus moluccana*, see (Hall et al., 2015)). This rapid decrease in *L* was evident in a quick increase in $\tau_d$ (Fig. 1). However, it recovered rapidly after rainfall in December 2014, resulting in a lower τ_d than before the insect attack. 

We compared calibrated $L_\tau$ to an independent estimate of *L* from canopy photos ($L_p$), which were collected nine times between Oct. 2012 and Oct. 2013. Without further calibration, the two estimates were reasonably well correlated, though the canopy photos gave slightly higher estimates of *L* (Fig. 2, R2=0.71, RMSE=0.12). This is encouraging because the photos measure *L* near the zenith (+/- 15°), while $L_\tau$ is integrated over the sky hemisphere (Eq. 3), weighted towards the zenith. 

We found no differences in the *L* anomaly between the $C_a$ treatments (Fig. 4) (p > 0.05), since the 95% confidence intervals of the generalized additive model overlapped. A linear mixed-effects model with $C_a$ and time as fixed effects, and FACE ring as a random effect also showed no significant effect of $C_a$ on the *L* anomaly (P > 0.2). What difference between $C_a$ treatments could we have reasonably detected? The average half-width of the confidence interval on the *L* anomaly (Fig. 4) was 0.047 m$^2$ m$^{-2}$ for $aC_a$, and 0.042 m$^2$ m$^{-2}$ for the $eC_a$ treatment. This means that, provided the within-treatment variance stays the same, we could detect a difference of 0.089 m$^2$ m$^{-2}$ (the sum of the half-width CI’s), or about a change of 6% over the mean *L* of the EucFACE (1.39 m$^2$ m$^{-2}$).

The dynamics of $L_\tau$ were compared with litter fall, by estimating the absolute change in $L_\tau$ for every FACE ring, for every period when litter was collected. We did this by fitting a generalized additive model to $L_\tau$ for each ring separately (similar to shown for $\tau_d$ in Fig. 1), and calculating the change in $L_\tau$ for each period ($\Delta L_\tau$). Litter production correlated significantly with $\Delta L_\tau$ when the latter was separated into periods where $\Delta L_\tau$ > 0 (net leaf growth) and $\Delta L_\tau$ <  0 (net leaf loss) (Fig. 5). During periods of net leaf loss, we found a significant correlation (with a slope of XX ± se, P < 0.001?, df or n?) close to the 1:1 line, as expected since no leaf growth was observed during any period where *L* was decreasing. During periods of net leaf growth, we found a significant correlation (slope, P, df…) between $\Delta L_\tau$ and litter production (Fig. 5). 

We found a significant correlation among FACE rings between litter production (averaged over the entire period) and mean *L*τ during the same period (Fig. 6a), which is expected if leaf lifespan is relatively constant. This allowed us estimate mean leaf lifespan from *L*τ and litter production as the ratio of *L*τ to annual litter production, yielding a mean lifespan of 0.95 yr, with no significant difference (P? F? df?) between $C_a$ treatments (Fig. 6b). 

Finally, we quantified the relationship between timing of leaf flushing and environmental drivers. During the XXX month study period, we observed four leaf flushing events in the field, with one before estimates of *L*τ were available (Fig. 7). These events occurred in spring and summer, with no clear annual cycle (Oct. 2012, Jan. 2013, Dec. 2013 and Jan. 2015). The dynamics of *L*τ from the sensor record matched these events observed in the field quite well (Fig. 6a), as estimated from a generalized additive model fitted to the average *L*τ across the six FACE rings. From the fitted model, we estimated the numerical derivative of *L* (dL/dt), as well as its confidence interval. All four leaf flushing events corresponded to significant positive derivative dL/dt. One brief significant positive dL/dt (June 2013) did not correspond to an actual leaf flushing event, but it was small in magnitude. It is also obvious that every leaf flush event occurred shortly after a heavy rainfall event (Fig. 4 and 6), when temperature was ???? and the soil water content in the top 80 cm increased to ca. > 0.2 m3 m-3. Two periods of sustained decrease in *L* (red lines in Fig. 7b, during winter of 2013 and 2014) corresponded to periods of low soil water availability.


# Discussion

## Response of *L* to elevated [$CO_2$]
We report on 28 months of continuous leaf area index (*L*) measurements in a native evergreen *Eucalyptus* woodland exposed to +150ppm elevated $CO_2$ ($eC_a$) and 3 months of ramp-up in $C_a$. We had predicted that *L* would increase in response to $eC_a$ as a result of increased quantum yield for photosynthesis, enhanced $CO_2$ assimilation for the entire canopy, and increased soil water availability. We also expected that this eucalypt woodland, with its inherently low *L* (Whitehead and Beadle, 2004), would be even more responsive to $eC_a$ than higher-*L* and more closed-canopy stands (Norby and Zak, 2011). Counter to our expectations but similar to Norby et al. (2003), we found no significant effect of elevated $C_a$ on *L*. It could be argued that the change in *L* in response to $eC_a$ was too small to be detected. Natural variation in *L* among plots in a native woodland is indeed a challenge to manipulative studies with low replication, such as FACE experiments. To increase sensitivity and statistical robustness, we used a novel method to account for pre-treatment differences by using stand basal area as a covariate. Using this method, we estimated that we can detect a difference of only a 6% in *L*. Based on this small detectable difference, we conclude that the lack of a significant $C_a$ effect is not due to a lack of power, but a true lack of response to elevated $C_a$.

This lack of a response to elevated $C_a$ counters our expectations and those in previous publications (Norby et al. 2003 McCarthy et al. 2007), for a number of reasons. First, in a review of forest FACE sites, Norby and Zak (2011) showed that low *L* stands are more responsive to $eC_a$. They argued that high *L* canopies would not benefit from further increases in *L*, because it would lead to only very small increases in total absorbed radiation. The mean *L* at the EucFACE was ca. 1.4 m$^2$ m$^{-2}$, which is low compared to a global compendium of forest *L* (Iio et al., 2013), and the lowest *L* of any forest FACE experiment (Norby and Zak, 2011), but in line with a range of values for native Eucalyptus forests and woodlands reported by (Whitehead and Beadle, 2004) and (Iio et al., 2013). Based on this *L* estimate and the relationship across FACE sites reported by Norby and Zak (2011), we could expect about a 30% increase in *L* under $eC_a$. It is clearly too early to draw general conclusions across FACE sites in terms of *L* response, moreover because water and nutrient likely play a central role in productivity and *L* dynamics at the EucFACE. Indeed, experimental evidence clearly demonstrates strong limitations of *L* by nutrients and water in Eucalyptus stands (White et al., 2010).

A possible explanation for the lack of a *L* response to $eC_a$ is that leaf growth may not be limited by carbon availability. In other words, stimulation of net leaf photosynthesis by $eC_a$ (a common response, also observed at the EucFACE, (Gimeno et al. in review) may not lead to increased net leaf growth, due to water or nutrient limitations (Crous et al., 2015). Net leaf growth is the net sum of allocation of photosynthates to leaf growth, and turnover of the leaf pool. Either process may itself be affected by $eC_a$ (De Kauwe et al. 2014, refs on turnover). We found no support for differences in leaf lifespan estimates based on *L* and litter production between $C_a$ treatments (Fig. 6), suggesting that during the study period leaf turnover rate was not affected by $eC_a$. To further understand the response of biomass allocation to $eC_a$ at the EucFACE, all components of the carbon balance must be carefully quantified, a task underway but not yet complete. For example, Drake et al. (in review) reported increased soil respiration under $eC_a$, suggesting that at least some of the stimulation of photosynthesis was allocated to either root growth, respiration, or root exudation.

##Continuous measurement of *L*
Studying canopy leaf area index in an evergreen natural woodland poses unique challenges. Unlike deciduous canopies, litter production cannot be used to estimate *L*, because leaf lifespan is unknown. We can also not rely on estimated leaf area based on allometric relationships with stem diameter or height, since these equations are not available for E. tereticornis, and besides these would be useless since *L* is highly variable temporally (Figs. 1, 4). We found that indirect estimates of *L* based on canopy transmittance were very reliable.  Estimated *L* compared well to that from flat canopy photos (cf. (Macfarlane et al., 2007) (Fig. 2), and after calibration, to leaf litter production during a dry period. Unlike canopy photos, PAR sensors do not need thresholding or time-consuming post-processing. We do argue that the raw data must be filtered by diffuse conditions, as the spatial and within-day variance are negligible compared to periods of direct sunshine (Chason et al., 1991)(Dufrêne and Bréda, 1995)(Nilson, 1999). When we used unfiltered canopy transmittance data, this yielded more distinct seasonal patterns in canopy transmittance (Fig. S1), because longer path lengths in the winter result in lower overall transmittance. Using diffuse PAR only avoids having to correct for these path length effects. 

## Litter production and dynamics of *L*
We found a correlation between *L* dynamics and litter production, both during periods of decreasing and increasing *L*. During a sustained period without significant rainfall (42 mm over 4 months), we used the decrease in *L* as an opportunity to calibrate against litter production. During periods of increasing *L*, litter fall increased sharply, indicating replacement of old leaves by young leaves. Indeed we observed in the field that after the significant flushing event of Dec. 2013, very few old leaves were present in the canopy. This is in line with (Pook, 1984a) in *Corymbia maculata* (a genus closely related to *Eucalyptus*), who showed accelerated litter production during periods of net *L* increase, but with a lag between litter fall and production of about 2 months. Similarly, (Stone and Bacon, 1995) showed that drought-stressed trees had higher litter production at the branch scale, but irrigated trees had larger litter production at the canopy scale. Since leaf flushing has been shown to be closely related to soil water availability (Fig. 7; Pook, 1984a), net leaf turnover is driven by water availability both through increased litter production during extended droughts, and complete canopy replacement following leaf flushing. The consequence is that leaf turnover is highly variable in time.

## Consequences for phenology models
Current-generation phenology models are heavily biased towards temperate conditions (Primack and Miller-Rushing, 2011), where leaf flushing occurs in spring in response to increase in temperature (Richardson et al., 2012; Savoy and Mackay, 2015). In contrast, phenology of evergreen Eucalyptus may be more opportunistic, and shows rapid response to water availability (Fig. 7). (Specht and Brouwer, 1975) demonstrated for four Eucalyptus species that leaf growth  peaked both in spring and autumn, with low winter temperatures and high summer temperatures (and low water availability) suppressing leaf growth. Similarly, (Pook, 1984b) demonstrated leaf production during most months in *Corymbia maculata*, except during winter and suppression by dry periods (Pook, 1984a). Thus a minimum temperature is also required for leaf growth to occur. We also have not observed leaf flushing in winter time (Ellsworth et al., unpubl. data), but at our site this was confounded with water availability as both winters during the study period were relatively dry (Fig. 7). 

Although the response of *L* to water availability is qualitatively well-known, current-generation phenology models fall short in incorporating this response. In a comparison of six leading ecosystem and global vegetation models,  (Powell et al., 2013) showed that the steady decrease in *L* in an Amazon drought experiment could be matched by only one model. Simulations from De Kauwe et al. (2014) at ambient and elevated $C_a$ also showed little response to inter-annual variation in rainfall (pers. comm. Martin De Kauwe). In most models  that provide prognostic estimates of *L* (i.e., excluding models that take *L* as an input parameter; e.g. (Kala et al., 2013)), temporal changes in *L* are modelled by first calculating total net photosynthetic productivity (carbon availability, gross photosynthesis minus respiration), and allocating some fraction to the leaf pool. Combined with - usually constant - leaf turnover and specific leaf area (ratio of leaf area to mass), this yields predictions of *L* in response to environmental drivers such as $eC_a$ (Fig. 2). We hypothesize that this algorithm is not well suited to explain the dynamic nature of *L* in response to water availability observed in evergreen broad-leaved forests, because not all important mechanisms are incorporated in these models. In order to construct a phenology model where phenology is responsive to water availability, it should include responses of both leaf turnover and leaf growth to fluctuating water availability. Water limitation is known to enhance leaf turnover (Pook et al.1997), possibly to maintain sufficient rates of water availability to the remaining leaves (Vilagrosa et al. 2003, Misson et al. 2010). Some existing ecosystem models allow for increased leaf turnover during periods of low water availability (e.g. G’DAY, see Corbeels et al. 2005), but this process has been poorly quantified. 

# Conclusions
Leaf area index (*L*) of a natural Eucalyptus woodland was unresponsive to elevated [$CO_2$] after 27 months of treatment and 24 months at +150ppm $CO_2$ elevation. Litter production was closely related to dynamics of *L*, both during dry periods (leading to accelerated litter production), and periods of net leaf growth (when old foliage was replaced by new foliage). We found no clear annual pattern in onset of leaf growth, instead, leaf growth consistently commenced after heavy rainfall following a dry period. Both the dynamics of litter production and the rapid response to soil water availability challenge current-generation prognostic *L* and phenology models. High resolution time series such as the one we present in this study should be used to develop new models of phenology for evergreen woodlands.

# Acknowledgments {.unnumbered}
Steven Wohl, Vinod Kumar, Craig Barton, litter collection: Andrew Gherlenda, Julia Cooke, Catherine Beattie
EucFACE is an initiative supported by the Australian Government through the Department of Industry and Science in partnership with the University of Western Sydney. Facilities and instrumentation at EucFACE were assembled as an initiative of the Australian Government as part of the Nation-building Economic Stimulus Package.


# References {.unnumbered}

