---
output: word_document
---
In this manuscript, Duursma et al. present findings on the response of LAI and litter production to elevated atmospheric CO2 in EucFACE, a free air CO2 enrichment experiment established in a Eucalyptus woodland. The authors had expected elevated CO2 to increase LAI and litter production. In contrast to these expectations, the authors found CO2 to have no significant effect on either LAI or litter production over the 28-month experiment. However, they did find that CO2 extended leaf lifespan by approximately two months.

Overall, it is my opinion that this manuscript is unsuitable for publication in Global Change Biology in its current form and should be rejected. I do not take this recommendation lightly, since data from forest CO2 enrichment experiments is highly valuable and in great demand. However, I have several issues with the field techniques and analyses addressed in this manuscript and the effort required to address them warrants the submission of an entirely new manuscript in my opinion.

The largest issue is that LAI anomaly (the main response analyzed) is essentially calculated from the mean of LAI over the experimental period. In an attempt to account for initial differences between plots, the authors correlated mean LAI and basal area for each plot. They then calculated the difference between the observed LAI and the expected value based on the LAI-BA relationship and defined it as “LAI anomaly.” However, because LAI and BA were so tightly correlated, this LAI anomaly is essentially the same as the difference between the mean LAI and the observed LAI. Since LAI means are the means of the observed values, all plots have a mean LAI anomaly of approximately zero (this can be seen in Fig. 3). This heavily restricts the ability of any statistical test to detect differences between plots or treatments. Thus, the finding of no response of LAI anomaly to elevated CO2 is not surprising.

**We now use pre-treatment BA as a covariate in a mixed-effects model. We found no CO2 or CO2 x time effect on LAI when BA was used as a covariate. There is also no effect of CO2 when BA is not included as a covariate, but due to the tight relationship between BA and LAI, using BA as a covariate increases the ability to find a CO2 effect. We only show the results when including BA as a covariate in the manuscript. Fig.2 now shows the LAI timeseries instead of the anomaly as before, and we have amended the text in various places to account for these changes.**

The only statistically significant response of LAI that would be expected under the current statistical design would be from a CO2 x time interaction. While no statistics are reported, an interaction may have been detected but attributed exclusively to an insect outbreak, whereas it also has the potential to due to a real response. However, the inclusion of the post-outbreak data makes this difficult to discern. The outbreak confounds the effect of CO2 with that of the outbreak, and thus data from the infested plot should only be considered up until the outbreak occurred.

**As noted above, we have redone the analysis and find no CO2 or CO2 x time effect. Although there was a brief period when the 95% confidence intervals were not overlapping (for the anomaly, though not when LAI is considered, see new Fig.2), this brief period did not result in a significant overall CO2 x time effect. For this reason we have not removed the insect attack from the study (it would have been appropriate if we did find a CO2 x time effect).**

The techniques used to collect litter are also concerning. The authors deployed eight 0.2 m2 litter traps in each ~123 m2 plot and used the litter collected from these traps to estimate litter production. However, considering the size of each individual trap and scale of the experiment, there is significant doubt that the traps provided a representative sample of each plot. Additionally, the analyses performed using litter data make several assumptions that are unlikely to hold.

**and**

l.160 “litter cloth basket” is odd. Where were they placed? This is a very small portion of the total plot area and indeed the area where litter would be expected to fall (an area much larger than the plot). So, these baskets are likely capturing only a tiny fraction of the litter from each plot and might even be catching litter from outside the plot as well, depending on where they are located. Can such a small and potentially contaminated sample be representative of such a large plot?

**The size, number, and relative coverage of the litterfall traps is broadly consistent with other forest FACE studies (see Table below), with the largest trap size. The size and coverage of the traps is therefore fully justified. The litter traps were placed in somewhat random locations across the ring, but never within XXX meters of the plot edge, to minimize contamination. We, as in all other FACE sites, cannot be completely certain that contamination did not occur, but it is likely that the vast majority of litter in each basket was produced in that FACE ring.**

```{r echo=FALSE}
tabl <- read.csv(text="Experiment,	Reference,	Nr Traps per plot,	Trap size (m2),	Plot size (m2),	Coverage (%)
Duke,Finzi et al. 2001,	12,	0.16,	908,	0.0021
Oak Ridge,Norby et al. 2003, 	7,	0.19,	491,	0.0027
PopFACE,Lagomarsino et al. 2013,	18,	0.13,	300, 0.0078
Rhinelander,Liu et al. 2009,	18,	0.145,	707,	0.0037
BangorFACE,Godbold et al. 2014,	7,	0.11,	57,	0.0136
EucFACE,this paper,	8,	0.1979,	491,	0.0032", header=TRUE, check.names=FALSE)

tabl <- tabl[,-ncol(tabl)]

library(knitr)
kable(tabl)
```

Another issue lies in the inclusion of an add-on analysis comparing two LAI estimation techniques. While useful, this comparison should be its own methods paper and does not align well with the scope of the rest of the manuscript. Currently, it adds to an already lengthy paper and distracts from the authors’ main points.

**We have moved this analysis, including the methods, to the Supporting Information. We believe this is interesting information for others concerned with LAI estimation, but agree it is a secondary objective only. We only briefly mention in the Methods that the two methods gave comparable results.**

**We are surprised that the reviewer considers our paper 'lengthy', as the word count of ca. 5500 words is more than 30% lower than the allowed length for Global Change Biology (8000 words).**

Finally, the manuscript requires extensive editing for structure and flow. 

**We have made substantial edits to the text, in particular accounting for the reviewer's comments listed below.**

The introduction does not sufficiently establish the expectation of litter responses. 

*TODO* **We have added a couple of sentences indicating the expectation of the litter response; it follows logically from the test of differences in LAI**

The methods are incomplete and unclear. Specifically, there are many portions of the Results section that should be included in Materials and Methods. 

**We have moved all methods-related content from the Results to the Methods section. We respond further to specific comments related to the Methods below**

Additionally, it is unclear if the authors’ used repeated measures to analyze their data, which would be necessary considering the experimental design. 

**Using a mixed-effects model as we have done (also in the original manuscript), with FACE ring as a random effect, accounts for the repeated measures nature of the data. We have clarified this in the Methods.**

Beyond these issues, the manuscript also should be revised for clarity and brevity.

**We have done so in response to specific comments listed below, and made more minor changes to increase clarity.**


Specific Comments (line number given):
  Abstract
l.26 What do you mean by (hot summer), and is it necessary? This is not how you describe the climate in the methods.

**Reworded to 'subtropical', which is more fitting** *IS THIS CORRECT*

l.30 “this timeframe” is a stretched reference (ref. l.24). Reword

**Removed 'in this timeframe'.**

l.31 You don’t provide expectation of a seasonal pattern in the abstract, so explaining that there isn’t one is distracting here.

**todo**

l.37 I would expect that GCB readers would know what FACE stands for, but it might be good to say free air CO2 enrichment to be safe.

**It was already defined at the top of the Abstract, when the term EucFACE is introduced.**

Introduction
l.40 Does it save a lot of space to abbreviate LAI as L or is there another reason for not using the conventional LAI? Unless there’s a strong reason to keep it as L, it would be more intuitive to have this as LAI.

**Changed to LAI throughout the manuscript.**

l.55 drop the “the” in “the water-use efficiency”

**Done.**

l.60 this would make a better topic sentence for this paragraph than the current one

**This sentence is now the topic sentence of the paragraph.**

l.69+ you can use stronger language here and throughout. If you expect X, say so. No need for “can” or “could.” Also, this is a very drawn-out sentence. The length of this sentence and others throughout weakens them and reduces their clarity. Be concise, particularly in your topic sentences.

**Edited the paragraph throughout.**

l.75 The meaning of Ca can be inferred from your definition of eCa, but it’s better to just write it out when you’re not using a defined term. So here, atmospheric [CO2]

**Done.**

l.79 This sentence is awkwardly constructed. Again, too long and an unclear topic sentence. If the point of this sentence is to set up a paragraph about water, why start it off talking about temperature and photo period? It would be better to frame this as quantitative water effects being relatively unknown as opposed to qualitative effects being well-known. I would just drop l.79-81, and start with “The response of L to fluctuations in water availability….” Issues like this need to be addressed throughout the paper.

**Edited the paragraph throughout (and deleted l.79-81).**

l.94 the tense of this paragraph is weird. You’re moving between your hypotheses (which should be present tense) to your methods (in past tense). This is makes it unclear which statements you’re making a priori.

**Edited the paragraph throughout, with special attention to tense.**

l.95 to eCa in the EucFace experiment. EucFace needs to be defined in the body of the manuscript

**FACE was defined in the 2nd paragraph of the definition, here the definition of EucFACE is quite obvious from the statement that the woodland is Eucalyptus-dominated**

l.97 are these means over the same period? This type of detail should be in the methods, not the introduction

**Removed info on precipitation and PET here, as it is explained in more detail in the Methods already.**

l.99 Because Production – Litter = LAI? Currently, the introduction doesn’t address litter fall, so why is this expected to change?

**If LAI changes, this must be due to changes in either the production of new foliage, or the lifespan of existing foliage. Both components can be assessed with measurements of litter production in combination with the time dynamics of LAI.** *Expand intro on litter fall a bit!!*

Materials and Methods
l.110 What do you mean by undisturbed? Be specific

**Added '(unmanaged)'.**

l.116 How accurate is this calculation? Are the P and PET values for the site or the region? Are they from different areas?

**The estimate of PET is used only here to give an estimate of the ratio P/PET as an indicator of long-term water limitation. The global PET database gives average PET based on 1950-2000 climatology, and is widely used to estimate PET across sites. It is beyond the scope of this manuscript to calculate more accurate estimates of PET, as we do not use PET in any of the subsequent analyses.**

l.136 unclear use of Ca

**Removed Ca.**

l.163 provide this calculation. Was it LAI (cm2/cm2) = SLA  (cm2/g) x Litter (g/cm2)?

**Changed the text to 'by multiplying it with an estimate of [...] SLA.**

l.206 The calibration is difficult to follow

**todo. which part is difficult???**

l.267 Was this set up as a repeated measures?

**The random ring effect accounts for the repeated measures structure of the data; we have now clarified this.**

l.269 The calculation of the anomaly is problematic. Ideally, it would be done considering some pre-treatment value or, less desirably, using a starting condition value. Since there is a strong correlation between mean LAI and BA, and the anomaly is currently based on values from this correlation, the mean anomaly of each plot is inherently very close to zero (this can be seen in Fig. 3). Thus, using the mean value from the experimental period inherently removes almost any possibility of there being a meaningful main treatment effect, since all rings are forced to have roughly the same mean anomaly over the course of the experiment. In contrast, anomalies calculated based on a pre-treatment values are not defined as having the same mean and therefore can reveal significant main effect differences.

**We have responded to the data analysis concerns above.**

Results
l.290 The insect outbreak confounds your results and is not something that you really set out to examine. Consider excluding ring 6 data from the outbreak onward.

**We disagree that the outbreak confounded the results; we did not find effects of CO2 on LAI despite the outbreak. Although we did not set out to examine the outbreak, it occurred nonetheless and we think it is informative as the outbreak reflects natural dynamics of Eucalyptus-dominated woodlands. Also, we do not discuss the outbreak in any sort of detail, so removing it from the figure does not shorten the manuscript.**

l.299 See above comments (a significant main Ca effect is almost impossible). A significant Ca x Date interaction is possible, but not reported here. However, if a significant interaction was found, it seems like it was likely attributed only to the insect outbreak in ring 6, but might also be due to Ca effects obscured by the current anomaly calculation.

**We have responded to the concerns about data analysis above.**

l.301+ move to the discussion

**We have moved the discussion of discernable effect sizes to the discussion.**

l.307 move to methods

**Done.**

l.314 Did you verify that there was no leaf growth, or is this an assumption based on drought?

**We verified in the field that no leaf growth was occurring. We have clarified this in this section as well as made reference to Fig. 6, where we have indicated when leaf growth was observed in the field.**

l.318 move to methods. This calculation assumes litter is grown and lost in the same time period. This is unlikely, especially since a month is an ecologically arbitrary duration. So, this calculation could indicate that a period of reduced Lt and large litter fall was associated with positive leaf production. However, the leaves lost as litter were likely produced over a variety of time points. This also ignores the problems of incomplete litter capture and non-experimental litter entering the plot.

**Moved to methods. We disagree that this method 'assumes litter is grown and lost in the same time period'. Basically, gross leaf production must be equal to the net change in LAI (=the pool of leaves in the canopy) plus the amount of shedded leaf area, as measured by litter production. And to  "this calculation could indicate that a period of reduced Lt and large litter fall was associated with positive leaf production", this is only true if the reduction in LAI is less than the litter produced. In that case the canopy must have produced new leaves in that period to complete the sum of dLAI/dt = leafgrowth - litter. There are no assumptions on when the leaves were produced that show up in the litter traps at that time.**

**We think that the term 'litter production' may be misleading, as the term 'production' seems to indicate that the leaves were 'produced' during that time period, which we certainly do not assume nor imply (in fact, we have shown that leaf lifespan is ca. 1 year).**

l.330 methods

**Done.**

l.333 methods

**Done.**


Discussion
l.361 Its somewhat misleading to claim that basal area was included as a covariate, since it was not actually included in any statistical analysis of a response variable.

**The previous analysis was essentially equivalent to using BA as a covariate, however this is now irrelevant since we have redone the analysis.**

l.368 There are a lot of places throughout the manuscript where you start a thought with “X showed Y response,” which puts the emphasis on the authors (X) and not the concept (Y). The points you’re trying to make are Y, not who showed them. This is not a huge problem, but the current emphases on authors and not concepts makes portions of the manuscript feel disjointed and list-y.

**The manuscript was edited throughout to make statements more direct.**

l.376 you originally expected that, but did not find it, right? Again, remove “could”

**Removed 'could'.**

l.377 “very” is redundant. How does this relate to the point you’re trying to make?

**Removed 'very'.**

l.378 The purpose of this manuscript was not to make broad generalizations on FACE L responses. This whole paragraph should be dropped.

**It was not the purpose of the manuscript to generalize to other FACE sites, but we feel it is relevant discussion to the results of this study to the other FACE sites. This is informative because the results from the EucFACE do not fit well with a generalization across other FACE sites as presented by Norby and Zak (2011).**

l.381-5 pick one of these two sentences

**Deleted sentence on line 381.**

l.388 eCa. Be consistent

**Done.**

l.389+ how does this support the message of this manuscript?

**Here we try to reconcile the apparent inconsistency : we found no effect of CO2 on LAI, but we did find a longer leaf lifespan in elevated CO2. This implies that the fractional allocation to leaves in elevated CO2 has decreased (through mass balance considerations). We have shortened this part of the paragraph.**

l.395 define LL earlier in the ms and use throughout

**We now define LL in the Methods and use it more consistently throughout.**

l.401+ Is the point what all these studies found specifically, or that there are mixed effects of eCa on LL?

**Edited the sentence for clarity.**

l.408 formatted as parenthetical reference

**Done.**


Figures: Consider using other colors to avoid problems for red/blue colorblind readers. This is a lot of figures, evaluate which ones are essential to the main points of the manuscript and put non-essential figures in supplements.

**We have moved Fig. 2 to the Supporting Information. We have retained the other figures as we feel they are essential to the manuscript (and six figures does not seem excessive to us).**

3: include a 1:1 line for positive values too.

**Done.**

4: Increase line thickness.

**todo**



